package com.jbaldridge.higherlower;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;
import android.widget.Toast;

import java.util.Random;

public class MainActivity extends AppCompatActivity {

    // creates a number
    Random rand = new Random();
    int save = rand.nextInt(20) + 1;

    public void getGuessNumber(View view)
    {
        EditText guessEditText = (EditText) findViewById(com.jbaldridge.higherlower.R.id.guessText);
        int guessInt = Integer.parseInt(guessEditText.getText().toString());
        // If the number that the user guessed is less than the number that was generated by
        // the computer
        if (guessInt < save)
        {
            Toast.makeText(MainActivity.this, "Too Low!", Toast.LENGTH_SHORT).show();
        }
        // If the guessed number was higher than the generated
        else if (guessInt > save)
        {
            Toast.makeText(MainActivity.this, "Too High!", Toast.LENGTH_SHORT).show();
        }
        // If the guessed number is the same as the generated
        else if (guessInt == save)
        {
            Toast.makeText(MainActivity.this, "Just Right!", Toast.LENGTH_SHORT).show();
            rand = new Random();
            save = rand.nextInt(20) + 1;
            Toast.makeText(MainActivity.this, "Now Try It Again!", Toast.LENGTH_SHORT).show();
        }
        // if, SOMEHOW, the guessed number is neither higher, lower, or equal to the generated
        else
        {
            // this shouldn't happen ever but just in case
        }
        //Toast.makeText(MainActivity.this, String.valueOf(save), Toast.LENGTH_LONG).show();
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);




    }
}
